### ISSUE TITLE
porque?

### ISSUE THREAD

**Issue by ZSendokame** [bypequeno/oneliner#1]
PORQUE ALAN DEL PASADO
PORQUE

**Comment by bypequeno** [comment]
AAAAAAAAAAAAAAAAAAAAAAAAAAAAA

**Comment by bypequeno** [comment]
Porque no mi estimado Sendo? 🤔

**Comment by ZSendokame** [comment]
Esta bien, funciona
Pero una linea hace que el codigo no sea legible y con ello empeore

**Comment by bypequeno** [comment]
Si.

**Comment by bypequeno** [comment]
Aver, imagina que un amigo te pide el codigo de un juego tipo piedra papel y tijeras en python, tu (un hdp) no mandarías esto:
`""" Rock Paper Scissors
----------------------------------------
"""
import random
import os
import re
os.system("cls" if os.name=="nt" else "clear")
while (1 < 2):
    print "\n"
    print "Rock, Paper, Scissors - Shoot!"
    userChoice = raw_input("Choose your weapon [R]ock], [P]aper, or [S]cissors: ")
    if not re.match("[SsRrPp]", userChoice):
        print "Please choose a letter:"
        print "[R]ock, [S]cissors or [P]aper."
        continue
    // Echo the user's choice
    print "You chose: " + userChoice
    choices = ['R', 'P', 'S']
    opponenetChoice = random.choice(choices)
    print "I chose: " + opponenetChoice
    if opponenetChoice == str.upper(userChoice):
        print "Tie! "
    #if opponenetChoice == str("R") and str.upper(userChoice) == "P"
    elif opponenetChoice == 'R' and userChoice.upper() == 'S':      
        print "Scissors beats rock, I win! "
        continue
    elif opponenetChoice == 'S' and userChoice.upper() == 'P':      
        print "Scissors beats paper! I win! "
        continue
    elif opponenetChoice == 'P' and userChoice.upper() == 'R':      
        print "Paper beat rock, I win! "
        continue
    else:       
        print "You win!"`
Sino, que gracias a este script, le puedes mandar esto:
`exec('""" Rock Paper Scissors\n----------------------------------------\n"""\nimport random\nimport os\nimport re\nos.system("cls" if os.name=="nt" else "clear")\nwhile (1 < 2):\n\tprint "\n"\n\tprint "Rock, Paper, Scissors - Shoot!"\n\tuserChoice = raw_input("Choose your weapon [R]ock], [P]aper, or [S]cissors: ")\n\tif not re.match("[SsRrPp]", userChoice):\n\t\tprint "Please choose a letter:"\n\t\tprint "[R]ock, [S]cissors or [P]aper."\n\t\tcontinue\n\t// Echo the user's choice\n\tprint "You chose: " + userChoice\n\tchoices = ['R', 'P', 'S']\n\topponenetChoice = random.choice(choices)\n\tprint "I chose: " + opponenetChoice\n\tif opponenetChoice == str.upper(userChoice):\n\t\tprint "Tie! "\n\t#if opponenetChoice == str("R") and str.upper(userChoice) == "P"\n\telif opponenetChoice == 'R' and userChoice.upper() == 'S':\n\t\tprint "Scissors beats rock, I win! "\n\t\tcontinue\n\telif opponenetChoice == 'S' and userChoice.upper() == 'P':\n\t\tprint "Scissors beats paper! I win! "\n\t\tcontinue\n\telif opponenetChoice == 'P' and userChoice.upper() == 'R':\n\t\tprint "Paper beat rock, I win! "\n\t\tcontinue\n\telse:\n\t\tprint "You win!"')`
y que se joda.

**Comment by bypequeno** [comment]
#### Aver, imagina que un amigo te pide el código de un juego en python:  
Tú (un hdp), obviamente no le mandarías esto:   
```python
""" Rock Paper Scissors
----------------------------------------
"""
import random
import os
import re
os.system("cls" if os.name=="nt" else "clear")
while (1 < 2):
    print "\n"
    print "Rock, Paper, Scissors - Shoot!"
    userChoice = raw_input("Choose your weapon [R]ock], [P]aper, or [S]cissors: ")
    if not re.match("[SsRrPp]", userChoice):
        print "Please choose a letter:"
        print "[R]ock, [S]cissors or [P]aper."
        continue
    // Echo the user's choice
    print "You chose: " + userChoice
    choices = ['R', 'P', 'S']
    opponenetChoice = random.choice(choices)
    print "I chose: " + opponenetChoice
    if opponenetChoice == str.upper(userChoice):
        print "Tie! "
    #if opponenetChoice == str("R") and str.upper(userChoice) == "P"
    elif opponenetChoice == 'R' and userChoice.upper() == 'S':      
        print "Scissors beats rock, I win! "
        continue
    elif opponenetChoice == 'S' and userChoice.upper() == 'P':      
        print "Scissors beats paper! I win! "
        continue
    elif opponenetChoice == 'P' and userChoice.upper() == 'R':      
        print "Paper beat rock, I win! "
        continue
    else:       
        print "You win!"
```
En cambio, gracias a este código, puedes mandarle esto:  
```python
exec('""" Rock Paper Scissors\n----------------------------------------\n"""\nimport random\nimport os\nimport re\nos.system("cls" if os.name=="nt" else "clear")\nwhile (1 < 2):\n\tprint "\n"\n\tprint "Rock, Paper, Scissors - Shoot!"\n\tuserChoice = raw_input("Choose your weapon [R]ock], [P]aper, or [S]cissors: ")\n\tif not re.match("[SsRrPp]", userChoice):\n\t\tprint "Please choose a letter:"\n\t\tprint "[R]ock, [S]cissors or [P]aper."\n\t\tcontinue\n\t// Echo the user's choice\n\tprint "You chose: " + userChoice\n\tchoices = ['R', 'P', 'S']\n\topponenetChoice = random.choice(choices)\n\tprint "I chose: " + opponenetChoice\n\tif opponenetChoice == str.upper(userChoice):\n\t\tprint "Tie! "\n\t#if opponenetChoice == str("R") and str.upper(userChoice) == "P"\n\telif opponenetChoice == 'R' and userChoice.upper() == 'S':\n\t\tprint "Scissors beats rock, I win! "\n\t\tcontinue\n\telif opponenetChoice == 'S' and userChoice.upper() == 'P':\n\t\tprint "Scissors beats paper! I win! "\n\t\tcontinue\n\telif opponenetChoice == 'P' and userChoice.upper() == 'R':\n\t\tprint "Paper beat rock, I win! "\n\t\tcontinue\n\telse:\n\t\tprint "You win!"')
```
### Y que se joda.

**Comment by ZSendokame** [comment]
De hecho si, le mandaria el codigo mas largo
El codigo aun que sea mas corto es mucho mas complicado de leer, actualizar y si hay errores generalmente veras codigo que use mas de una linea, no solo una
