### ISSUE TITLE
The program fails if `"` is present

### ISSUE THREAD

**Issue by fredrare** [bypequeno/oneliner#2]
When feeding the program a source file with `"` character delimiting a string, a `SyntaxError` is produced.

Example input code:
```py
print("hi")
```

Output code:
```py
exec("print("hi")")
```

Error:
```txt
  File "/Users/fredrare/tests/test_output.py", line 1
    exec("print("hi")")
                 ^
SyntaxError: invalid syntax
```

As you can see, the aforementioned character closes the opening `"` and ends the string, rendering the rest of the code that should be *inside* the string an error. Thus, the `h` is invalid in that position.

**Comment by bypequeno** [comment]
Thanks fredare, it's solved in the new version.
